version: '3'
services:
  todotests:
    image: todotests
    command: sh
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront

  todofront:
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    command: sh
    ports:
      - 3000:3000

  todoback:
    image: todobackend
    command: sh
    ports:
      - 3001:3001
